name: MobileProject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.8
  dropdown_search: ^0.4.8
  charts_flutter: ^0.8.1
  get: ^3.21.1
  circle_chart: ^0.0.3
  step_progress_indicator: ^0.2.5+8
  badges: ^1.1.4
  pie_chart: ^3.1.1
  syncfusion_flutter_calendar: ^18.3.52
  flutter_search_bar: ^2.1.0
  http: ^0.12.2
  date_format: ^1.0.9
  month_picker_dialog: ^0.3.3
  intl: ^0.16.1
  simple_bar_graph: ^0.1.2
  start_chart: ^0.2.0
  nuts_activity_indicator: ^0.1.1
  multi_charts: ^0.2.0
  shared_preferences: ^0.5.12+2
  scaled_animated_scaffold: ^0.0.6
  

 
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/userpng.png
    - assets/images/fit.png
    - assets/images/fitnew.png
    - assets/images/bgcard.jpg
    - assets/images/default.jpg
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CASTELAR
      fonts:
         - asset: assets/fonts/CASTELAR.ttf
         
         
    - family: Spectral
      fonts:
         - asset: assets/fonts/Spectral-MediumItalic.ttf

         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
